### PR TITLE
Display data from the category objects on index.php

### PR DESCRIPTION
**Pull request by gminovska**
I added a loop that grabs the objects' properties and displays then on the page. 

This is an infant state of our index page. Lacks  HTML (header and footer includes) and CSS. The subcategories link is there but currently doesn't lead anywhere since the subcategory_list.php page is not built yet.

I included a snapshot in the readme.md.

### CODE REVIEW

**Comment by gminovska** [comment]
Created the subcategory class and the related categories_list.php page. 
I uploaded a demo to my server: [Click Here](http://www.gordanaminovska.com/itc250/NewsAggregator/)

**Review by atkozie — APPROVED** [review]
This is great, it should be very easy to plug in to the static styled page I made. That's in my repo currently.

Do you think a footer is necessary? I was assuming we wouldn't need one.

**Comment by gminovska** [comment]
@atkozie I don't think a footer is necessary.

**Comment by nataliewang919** [comment]
Very good code. I like the WALL-E pic by the way.

**Pull request merged**
